name: goox_desktop
description: "Desktop shell for the goox editor."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  google_fonts: ^8.0.2
  path: ^1.9.1
  file_picker: ^10.3.10
  goox_editor_sdk:
    path: ../../packages/goox_editor_sdk
  goox_ui_shared:
    path: ../../packages/goox_ui_shared
  path_provider: ^2.1.5
  flutter_svg: ^2.2.4
  desktop_drop: ^0.4.4
  atomic_webview: ^0.1.2
  objectbox: ^5.3.0
  objectbox_flutter_libs: ^5.3.0
  cross_file: ^0.3.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  goox_flutter_bridge:
    path: ../../platform/flutter_bridge
  build_runner: ^2.13.1
  objectbox_generator: ^5.3.0

flutter:
  uses-material-design: true
  assets:
    - launch_assets/
    - assets/webview/
