import 'package:flutter/foundation.dart';

// ---------------------------------------------------------------------------
// Language Definition — describes syntax rules for a single language
// ---------------------------------------------------------------------------

@immutable
class LanguageDefinition {
  const LanguageDefinition({
    required this.keywords,
    this.builtinTypes = const {},
    this.builtinConstants = const {},
    this.builtinFunctions = const {},
    this.annotationPrefix,
    this.lineCommentPrefix,
    this.blockCommentStart,
    this.blockCommentEnd,
    this.stringDelimiters = const {"'", '"'},
    this.tripleQuoteDelimiters = const {},
    this.templateStringDelimiter,
    this.hashComment = false,
  });

  /// Control-flow and declaration keywords (if, for, class, etc.)
  final Set<String> keywords;

  /// Built-in type names (int, String, bool, etc.)
  final Set<String> builtinTypes;

  /// Built-in constants (true, false, null, etc.)
  final Set<String> builtinConstants;

  /// Built-in functions (print, len, etc.)
  final Set<String> builtinFunctions;

  /// Prefix for annotations/decorators, e.g. `@` for Dart/Java, `#` not used here.
  final String? annotationPrefix;

  /// Single-line comment prefix, e.g. `//` or `#`.
  final String? lineCommentPrefix;

  /// Block comment start token, e.g. `/*`.
  final String? blockCommentStart;

  /// Block comment end token, e.g. `*/`.
  final String? blockCommentEnd;

  /// Quote characters that start/end strings, e.g. `'`, `"`.
  final Set<String> stringDelimiters;

  /// Triple-quote delimiters for multiline strings, e.g. `'''`, `"""`.
  final Set<String> tripleQuoteDelimiters;

  /// Template literal delimiter, e.g. `` ` `` for JS/TS.
  final String? templateStringDelimiter;

  /// Whether `#` is a line-comment character (Python, Shell, etc.).
  final bool hashComment;

  bool get hasBlockComment =>
      blockCommentStart != null && blockCommentEnd != null;
}

// ---------------------------------------------------------------------------
// Language Definition Registry — static lookup for known languages
// ---------------------------------------------------------------------------

class LanguageDefinitionRegistry {
  LanguageDefinitionRegistry._();

  static LanguageDefinition? getDefinition(String? languageId) {
    if (languageId == null) return null;
    final id = languageId.trim().toLowerCase();
    return _definitions[id];
  }

  /// A generic C-like fallback for unknown languages that still deserve
  /// basic highlighting (// comments, /* */ blocks, standard strings).
  static const LanguageDefinition fallback = LanguageDefinition(
    keywords: {},
    lineCommentPrefix: '//',
    blockCommentStart: '/*',
    blockCommentEnd: '*/',
  );

  static const Map<String, LanguageDefinition> _definitions = {
    // ── Dart ──────────────────────────────────────────────────────────────
    'dart': LanguageDefinition(
      lineCommentPrefix: '//',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      tripleQuoteDelimiters: {"'''", '"""'},
      annotationPrefix: '@',
      keywords: {
        'abstract',
        'as',
        'assert',
        'async',
        'await',
        'base',
        'break',
        'case',
        'catch',
        'class',
        'const',
        'continue',
        'covariant',
        'default',
        'deferred',
        'do',
        'else',
        'enum',
        'export',
        'extends',
        'extension',
        'external',
        'factory',
        'final',
        'finally',
        'for',
        'get',
        'hide',
        'if',
        'implements',
        'import',
        'in',
        'interface',
        'is',
        'late',
        'library',
        'mixin',
        'new',
        'on',
        'operator',
        'part',
        'required',
        'rethrow',
        'return',
        'sealed',
        'set',
        'show',
        'static',
        'super',
        'switch',
        'sync',
        'this',
        'throw',
        'try',
        'typedef',
        'var',
        'when',
        'while',
        'with',
        'yield',
      },
      builtinTypes: {
        'int',
        'double',
        'num',
        'String',
        'bool',
        'List',
        'Map',
        'Set',
        'Future',
        'Stream',
        'Iterable',
        'Object',
        'dynamic',
        'void',
        'Never',
        'Function',
        'Type',
        'Symbol',
        'Null',
        'Record',
        'BigInt',
        'DateTime',
        'Duration',
        'Uri',
        'RegExp',
        'Error',
        'Exception',
        'Iterator',
        'Comparable',
        'Pattern',
        'Match',
        'Sink',
        'StateError',
        'TypeError',
        'ArgumentError',
        'RangeError',
        'UnsupportedError',
        'UnimplementedError',
        'FormatException',
        'StackTrace',
        'Stopwatch',
        'StringBuffer',
        'StringSink',
        'Expando',
        'WeakReference',
        'Finalizer',
      },
      builtinConstants: {
        'true',
        'false',
        'null',
      },
      builtinFunctions: {
        'print',
        'identical',
      },
    ),

    // ── Python ────────────────────────────────────────────────────────────
    'python': LanguageDefinition(
      hashComment: true,
      lineCommentPrefix: '#',
      tripleQuoteDelimiters: {"'''", '"""'},
      annotationPrefix: '@',
      keywords: {
        'and',
        'as',
        'assert',
        'async',
        'await',
        'break',
        'class',
        'continue',
        'def',
        'del',
        'elif',
        'else',
        'except',
        'finally',
        'for',
        'from',
        'global',
        'if',
        'import',
        'in',
        'is',
        'lambda',
        'nonlocal',
        'not',
        'or',
        'pass',
        'raise',
        'return',
        'try',
        'while',
        'with',
        'yield',
      },
      builtinTypes: {
        'int',
        'float',
        'complex',
        'str',
        'bytes',
        'bytearray',
        'bool',
        'list',
        'tuple',
        'set',
        'frozenset',
        'dict',
        'range',
        'memoryview',
        'type',
        'object',
      },
      builtinConstants: {
        'True',
        'False',
        'None',
      },
      builtinFunctions: {
        'abs',
        'all',
        'any',
        'ascii',
        'bin',
        'breakpoint',
        'callable',
        'chr',
        'classmethod',
        'compile',
        'delattr',
        'dir',
        'divmod',
        'enumerate',
        'eval',
        'exec',
        'filter',
        'format',
        'getattr',
        'globals',
        'hasattr',
        'hash',
        'help',
        'hex',
        'id',
        'input',
        'isinstance',
        'issubclass',
        'iter',
        'len',
        'locals',
        'map',
        'max',
        'min',
        'next',
        'oct',
        'open',
        'ord',
        'pow',
        'print',
        'property',
        'repr',
        'reversed',
        'round',
        'setattr',
        'slice',
        'sorted',
        'staticmethod',
        'sum',
        'super',
        'vars',
        'zip',
      },
    ),

    // ── JavaScript ────────────────────────────────────────────────────────
    'javascript': _jsDefinition,
    'js': _jsDefinition,

    // ── TypeScript ────────────────────────────────────────────────────────
    'typescript': _tsDefinition,
    'ts': _tsDefinition,

    // ── Rust ──────────────────────────────────────────────────────────────
    'rust': LanguageDefinition(
      lineCommentPrefix: '//',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      stringDelimiters: {'"'},
      keywords: {
        'as',
        'async',
        'await',
        'break',
        'const',
        'continue',
        'crate',
        'dyn',
        'else',
        'enum',
        'extern',
        'fn',
        'for',
        'if',
        'impl',
        'in',
        'let',
        'loop',
        'match',
        'mod',
        'move',
        'mut',
        'pub',
        'ref',
        'return',
        'self',
        'static',
        'struct',
        'super',
        'trait',
        'type',
        'unsafe',
        'use',
        'where',
        'while',
      },
      builtinTypes: {
        'i8',
        'i16',
        'i32',
        'i64',
        'i128',
        'isize',
        'u8',
        'u16',
        'u32',
        'u64',
        'u128',
        'usize',
        'f32',
        'f64',
        'bool',
        'char',
        'str',
        'String',
        'Self',
        'Vec',
        'Option',
        'Result',
        'Box',
        'Rc',
        'Arc',
        'Cell',
        'RefCell',
        'HashMap',
        'HashSet',
        'BTreeMap',
        'BTreeSet',
        'VecDeque',
        'LinkedList',
        'BinaryHeap',
        'Cow',
        'Pin',
        'PhantomData',
      },
      builtinConstants: {
        'true',
        'false',
        'Some',
        'None',
        'Ok',
        'Err',
      },
      builtinFunctions: {
        'println',
        'eprintln',
        'print',
        'eprint',
        'format',
        'panic',
        'todo',
        'unimplemented',
        'unreachable',
        'assert',
        'assert_eq',
        'assert_ne',
        'dbg',
        'vec',
        'cfg',
        'include',
        'include_str',
        'include_bytes',
        'env',
        'concat',
        'stringify',
        'line',
        'column',
        'file',
        'module_path',
      },
    ),

    // ── Go ────────────────────────────────────────────────────────────────
    'go': LanguageDefinition(
      lineCommentPrefix: '//',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      stringDelimiters: {'"'},
      templateStringDelimiter: '`',
      keywords: {
        'break',
        'case',
        'chan',
        'const',
        'continue',
        'default',
        'defer',
        'else',
        'fallthrough',
        'for',
        'func',
        'go',
        'goto',
        'if',
        'import',
        'interface',
        'map',
        'package',
        'range',
        'return',
        'select',
        'struct',
        'switch',
        'type',
        'var',
      },
      builtinTypes: {
        'bool',
        'byte',
        'complex64',
        'complex128',
        'error',
        'float32',
        'float64',
        'int',
        'int8',
        'int16',
        'int32',
        'int64',
        'rune',
        'string',
        'uint',
        'uint8',
        'uint16',
        'uint32',
        'uint64',
        'uintptr',
        'any',
        'comparable',
      },
      builtinConstants: {
        'true',
        'false',
        'nil',
        'iota',
      },
      builtinFunctions: {
        'append',
        'cap',
        'clear',
        'close',
        'complex',
        'copy',
        'delete',
        'imag',
        'len',
        'make',
        'max',
        'min',
        'new',
        'panic',
        'print',
        'println',
        'real',
        'recover',
      },
    ),

    // ── C ─────────────────────────────────────────────────────────────────
    'c': _cDefinition,

    // ── C++ ───────────────────────────────────────────────────────────────
    'cpp': _cppDefinition,
    'c++': _cppDefinition,

    // ── Java ──────────────────────────────────────────────────────────────
    'java': LanguageDefinition(
      lineCommentPrefix: '//',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      annotationPrefix: '@',
      keywords: {
        'abstract',
        'assert',
        'break',
        'case',
        'catch',
        'class',
        'continue',
        'default',
        'do',
        'else',
        'enum',
        'extends',
        'final',
        'finally',
        'for',
        'goto',
        'if',
        'implements',
        'import',
        'instanceof',
        'interface',
        'native',
        'new',
        'package',
        'private',
        'protected',
        'public',
        'return',
        'static',
        'strictfp',
        'super',
        'switch',
        'synchronized',
        'this',
        'throw',
        'throws',
        'transient',
        'try',
        'volatile',
        'while',
      },
      builtinTypes: {
        'boolean',
        'byte',
        'char',
        'double',
        'float',
        'int',
        'long',
        'short',
        'void',
        'String',
        'Object',
        'Integer',
        'Long',
        'Double',
        'Float',
        'Boolean',
        'Character',
        'Byte',
        'Short',
        'Void',
      },
      builtinConstants: {
        'true',
        'false',
        'null',
      },
    ),

    // ── JSON ──────────────────────────────────────────────────────────────
    'json': LanguageDefinition(
      stringDelimiters: {'"'},
      keywords: {},
      builtinConstants: {'true', 'false', 'null'},
    ),

    // ── YAML ──────────────────────────────────────────────────────────────
    'yaml': _yamlDefinition,
    'yml': _yamlDefinition,

    // ── TOML ──────────────────────────────────────────────────────────────
    'toml': LanguageDefinition(
      hashComment: true,
      lineCommentPrefix: '#',
      tripleQuoteDelimiters: {"'''", '"""'},
      keywords: {},
      builtinConstants: {'true', 'false'},
    ),

    // ── Shell / Bash ──────────────────────────────────────────────────────
    'shell': _shellDefinition,
    'bash': _shellDefinition,
    'sh': _shellDefinition,
    'zsh': _shellDefinition,

    // ── HTML ──────────────────────────────────────────────────────────────
    'html': LanguageDefinition(
      blockCommentStart: '<!--',
      blockCommentEnd: '-->',
      keywords: {},
    ),
    'xml': LanguageDefinition(
      blockCommentStart: '<!--',
      blockCommentEnd: '-->',
      keywords: {},
    ),

    // ── CSS ───────────────────────────────────────────────────────────────
    'css': LanguageDefinition(
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      keywords: {
        'important',
        'inherit',
        'initial',
        'none',
        'unset',
        'auto',
      },
    ),

    // ── Markdown ──────────────────────────────────────────────────────────
    'markdown': LanguageDefinition(keywords: {}),
    'md': LanguageDefinition(keywords: {}),

    // ── Kotlin ────────────────────────────────────────────────────────────
    'kotlin': LanguageDefinition(
      lineCommentPrefix: '//',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      annotationPrefix: '@',
      keywords: {
        'abstract',
        'as',
        'break',
        'by',
        'catch',
        'class',
        'companion',
        'const',
        'constructor',
        'continue',
        'data',
        'do',
        'else',
        'enum',
        'final',
        'finally',
        'for',
        'fun',
        'if',
        'import',
        'in',
        'init',
        'inner',
        'interface',
        'internal',
        'is',
        'lateinit',
        'object',
        'open',
        'operator',
        'out',
        'override',
        'package',
        'private',
        'protected',
        'public',
        'return',
        'sealed',
        'super',
        'suspend',
        'this',
        'throw',
        'try',
        'typealias',
        'val',
        'var',
        'when',
        'while',
      },
      builtinTypes: {
        'Int',
        'Long',
        'Short',
        'Byte',
        'Float',
        'Double',
        'Char',
        'Boolean',
        'String',
        'Unit',
        'Nothing',
        'Any',
        'Array',
        'List',
        'Map',
        'Set',
        'Pair',
        'Triple',
      },
      builtinConstants: {
        'true',
        'false',
        'null',
      },
    ),

    // ── Swift ─────────────────────────────────────────────────────────────
    'swift': LanguageDefinition(
      lineCommentPrefix: '//',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      annotationPrefix: '@',
      keywords: {
        'associatedtype',
        'break',
        'case',
        'catch',
        'class',
        'continue',
        'default',
        'defer',
        'deinit',
        'do',
        'else',
        'enum',
        'extension',
        'fallthrough',
        'fileprivate',
        'for',
        'func',
        'guard',
        'if',
        'import',
        'in',
        'init',
        'inout',
        'internal',
        'is',
        'let',
        'open',
        'operator',
        'private',
        'protocol',
        'public',
        'repeat',
        'return',
        'self',
        'static',
        'struct',
        'subscript',
        'super',
        'switch',
        'throw',
        'throws',
        'try',
        'typealias',
        'var',
        'where',
        'while',
      },
      builtinTypes: {
        'Int',
        'Int8',
        'Int16',
        'Int32',
        'Int64',
        'UInt',
        'UInt8',
        'UInt16',
        'UInt32',
        'UInt64',
        'Float',
        'Double',
        'Bool',
        'String',
        'Character',
        'Array',
        'Dictionary',
        'Set',
        'Optional',
        'Any',
        'AnyObject',
        'Self',
        'Void',
      },
      builtinConstants: {
        'true',
        'false',
        'nil',
      },
      builtinFunctions: {
        'print',
        'debugPrint',
        'dump',
        'fatalError',
        'precondition',
        'preconditionFailure',
        'assert',
        'assertionFailure',
        'min',
        'max',
        'abs',
        'zip',
        'stride',
        'sequence',
        'type',
        'swap',
        'withUnsafePointer',
      },
    ),

    // ── PHP ───────────────────────────────────────────────────────────────
    'php': LanguageDefinition(
      lineCommentPrefix: '//',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      hashComment: true,
      keywords: {
        'abstract',
        'and',
        'as',
        'break',
        'callable',
        'case',
        'catch',
        'class',
        'clone',
        'const',
        'continue',
        'declare',
        'default',
        'do',
        'echo',
        'else',
        'elseif',
        'enddeclare',
        'endfor',
        'endforeach',
        'endif',
        'endswitch',
        'endwhile',
        'extends',
        'final',
        'finally',
        'fn',
        'for',
        'foreach',
        'function',
        'global',
        'goto',
        'if',
        'implements',
        'include',
        'instanceof',
        'interface',
        'match',
        'namespace',
        'new',
        'or',
        'private',
        'protected',
        'public',
        'readonly',
        'require',
        'return',
        'static',
        'switch',
        'this',
        'throw',
        'trait',
        'try',
        'use',
        'var',
        'while',
        'xor',
        'yield',
      },
      builtinConstants: {
        'true',
        'false',
        'null',
      },
    ),

    // ── Ruby ──────────────────────────────────────────────────────────────
    'ruby': LanguageDefinition(
      lineCommentPrefix: '#',
      hashComment: true,
      keywords: {
        'alias',
        'and',
        'begin',
        'break',
        'case',
        'class',
        'def',
        'defined?',
        'do',
        'else',
        'elsif',
        'end',
        'ensure',
        'for',
        'if',
        'in',
        'module',
        'next',
        'not',
        'or',
        'redo',
        'rescue',
        'retry',
        'return',
        'self',
        'super',
        'then',
        'unless',
        'until',
        'when',
        'while',
        'yield',
      },
      builtinConstants: {
        'true',
        'false',
        'nil',
        '__FILE__',
        '__LINE__',
        '__ENCODING__',
      },
      builtinFunctions: {
        'puts',
        'print',
        'p',
        'require',
        'raise',
        'attr_reader',
        'attr_writer',
        'attr_accessor',
        'include',
        'extend',
        'lambda',
        'proc',
      },
    ),

    // ── Lua ───────────────────────────────────────────────────────────────
    'lua': LanguageDefinition(
      lineCommentPrefix: '--',
      blockCommentStart: '--[[',
      blockCommentEnd: ']]',
      keywords: {
        'and',
        'break',
        'do',
        'else',
        'elseif',
        'end',
        'for',
        'function',
        'goto',
        'if',
        'in',
        'local',
        'not',
        'or',
        'repeat',
        'return',
        'then',
        'until',
        'while',
      },
      builtinConstants: {
        'true',
        'false',
        'nil',
      },
      builtinFunctions: {
        'print',
        'type',
        'tostring',
        'tonumber',
        'pairs',
        'ipairs',
        'next',
        'select',
        'unpack',
        'table',
        'string',
        'math',
        'io',
        'os',
        'error',
        'pcall',
        'xpcall',
        'assert',
        'require',
        'dofile',
        'loadfile',
        'rawget',
        'rawset',
        'rawequal',
        'setmetatable',
        'getmetatable',
      },
    ),

    // ── SQL ───────────────────────────────────────────────────────────────
    'sql': LanguageDefinition(
      lineCommentPrefix: '--',
      blockCommentStart: '/*',
      blockCommentEnd: '*/',
      keywords: {
        'SELECT',
        'FROM',
        'WHERE',
        'INSERT',
        'UPDATE',
        'DELETE',
        'CREATE',
        'ALTER',
        'DROP',
        'TABLE',
        'INDEX',
        'VIEW',
        'INTO',
        'VALUES',
        'SET',
        'AND',
        'OR',
        'NOT',
        'IN',
        'IS',
        'NULL',
        'LIKE',
        'BETWEEN',
        'JOIN',
        'INNER',
        'LEFT',
        'RIGHT',
        'OUTER',
        'ON',
        'AS',
        'ORDER',
        'BY',
        'GROUP',
        'HAVING',
        'LIMIT',
        'OFFSET',
        'UNION',
        'ALL',
        'DISTINCT',
        'EXISTS',
        'CASE',
        'WHEN',
        'THEN',
        'ELSE',
        'END',
        'IF',
        'BEGIN',
        'COMMIT',
        'ROLLBACK',
        'TRANSACTION',
        'PRIMARY',
        'KEY',
        'FOREIGN',
        'REFERENCES',
        'CONSTRAINT',
        'DEFAULT',
        'CHECK',
        'UNIQUE',
        'CASCADE',
        'GRANT',
        'REVOKE',
        // lowercase variants
        'select',
        'from',
        'where',
        'insert',
        'update',
        'delete',
        'create',
        'alter',
        'drop',
        'table',
        'join',
        'inner',
        'left',
        'right',
        'outer',
        'on',
        'as',
        'and',
        'or',
        'not',
        'in',
        'is',
        'null',
        'like',
        'between',
        'order',
        'by',
        'group',
        'having',
        'limit',
        'into',
        'values',
        'set',
      },
      builtinTypes: {
        'INTEGER',
        'TEXT',
        'REAL',
        'BLOB',
        'VARCHAR',
        'CHAR',
        'BOOLEAN',
        'DATE',
        'TIMESTAMP',
        'DECIMAL',
        'FLOAT',
        'DOUBLE',
        'BIGINT',
        'SMALLINT',
        'SERIAL',
      },
      builtinConstants: {
        'TRUE',
        'FALSE',
        'NULL',
        'true',
        'false',
      },
      builtinFunctions: {
        'COUNT',
        'SUM',
        'AVG',
        'MIN',
        'MAX',
        'COALESCE',
        'NULLIF',
        'CAST',
        'CONVERT',
        'UPPER',
        'LOWER',
        'TRIM',
        'LENGTH',
        'SUBSTRING',
        'CONCAT',
        'REPLACE',
        'NOW',
        'CURRENT_DATE',
        'CURRENT_TIMESTAMP',
      },
    ),
  };

  // ── Shared definitions ──────────────────────────────────────────────────

  static const _jsDefinition = LanguageDefinition(
    lineCommentPrefix: '//',
    blockCommentStart: '/*',
    blockCommentEnd: '*/',
    templateStringDelimiter: '`',
    keywords: _jsKeywords,
    builtinTypes: {
      'Array',
      'Boolean',
      'Date',
      'Error',
      'Function',
      'Map',
      'Number',
      'Object',
      'Promise',
      'Proxy',
      'RegExp',
      'Set',
      'String',
      'Symbol',
      'WeakMap',
      'WeakSet',
      'WeakRef',
      'BigInt',
      'ArrayBuffer',
      'SharedArrayBuffer',
      'DataView',
      'Float32Array',
      'Float64Array',
      'Int8Array',
      'Int16Array',
      'Int32Array',
      'Uint8Array',
      'Uint16Array',
      'Uint32Array',
    },
    builtinConstants: {
      'true',
      'false',
      'null',
      'undefined',
      'NaN',
      'Infinity',
    },
    builtinFunctions: {
      'console',
      'parseInt',
      'parseFloat',
      'isNaN',
      'isFinite',
      'decodeURI',
      'decodeURIComponent',
      'encodeURI',
      'encodeURIComponent',
      'eval',
      'setTimeout',
      'setInterval',
      'clearTimeout',
      'clearInterval',
      'fetch',
      'require',
      'JSON',
      'Math',
    },
  );

  static const _tsDefinition = LanguageDefinition(
    lineCommentPrefix: '//',
    blockCommentStart: '/*',
    blockCommentEnd: '*/',
    templateStringDelimiter: '`',
    keywords: {
      ..._jsKeywords,
      'abstract',
      'as',
      'declare',
      'enum',
      'from',
      'implements',
      'interface',
      'is',
      'keyof',
      'module',
      'namespace',
      'of',
      'private',
      'protected',
      'public',
      'readonly',
      'type',
      'override',
      'satisfies',
      'infer',
    },
    builtinTypes: {
      'any',
      'boolean',
      'never',
      'number',
      'object',
      'string',
      'symbol',
      'unknown',
      'void',
      'bigint',
      'Array',
      'Map',
      'Set',
      'Promise',
      'Record',
      'Partial',
      'Required',
      'Readonly',
      'Pick',
      'Omit',
      'Exclude',
      'Extract',
      'NonNullable',
      'ReturnType',
      'InstanceType',
      'Parameters',
      'ConstructorParameters',
      'Awaited',
    },
    builtinConstants: {
      'true',
      'false',
      'null',
      'undefined',
      'NaN',
      'Infinity',
    },
  );

  static const Set<String> _jsKeywords = {
    'async',
    'await',
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'debugger',
    'default',
    'delete',
    'do',
    'else',
    'export',
    'extends',
    'finally',
    'for',
    'function',
    'if',
    'import',
    'in',
    'instanceof',
    'let',
    'new',
    'return',
    'super',
    'switch',
    'this',
    'throw',
    'try',
    'typeof',
    'var',
    'void',
    'while',
    'with',
    'yield',
  };

  static const _shellDefinition = LanguageDefinition(
    hashComment: true,
    lineCommentPrefix: '#',
    keywords: {
      'case',
      'do',
      'done',
      'elif',
      'else',
      'esac',
      'exit',
      'export',
      'fi',
      'for',
      'function',
      'if',
      'in',
      'local',
      'readonly',
      'return',
      'select',
      'shift',
      'source',
      'then',
      'trap',
      'until',
      'while',
    },
    builtinConstants: {
      'true',
      'false',
    },
    builtinFunctions: {
      'echo',
      'printf',
      'read',
      'cd',
      'pwd',
      'test',
      'eval',
      'exec',
      'set',
      'unset',
    },
  );

  static const _cDefinition = LanguageDefinition(
    lineCommentPrefix: '//',
    blockCommentStart: '/*',
    blockCommentEnd: '*/',
    keywords: _cKeywords,
    builtinTypes: {
      'char',
      'double',
      'float',
      'int',
      'long',
      'short',
      'signed',
      'unsigned',
      'void',
      'size_t',
      'ssize_t',
      'ptrdiff_t',
      'intptr_t',
      'uintptr_t',
      'int8_t',
      'int16_t',
      'int32_t',
      'int64_t',
      'uint8_t',
      'uint16_t',
      'uint32_t',
      'uint64_t',
      'bool',
      'FILE',
    },
    builtinConstants: {
      'NULL',
      'EOF',
      'true',
      'false',
      'stdin',
      'stdout',
      'stderr',
    },
    builtinFunctions: {
      'printf',
      'scanf',
      'fprintf',
      'fscanf',
      'sprintf',
      'sscanf',
      'malloc',
      'calloc',
      'realloc',
      'free',
      'memcpy',
      'memset',
      'memmove',
      'strlen',
      'strcmp',
      'strcpy',
      'strcat',
      'strstr',
      'sizeof',
      'exit',
      'abort',
      'atoi',
      'atof',
    },
  );

  static const Set<String> _cKeywords = {
    'auto',
    'break',
    'case',
    'const',
    'continue',
    'default',
    'do',
    'else',
    'enum',
    'extern',
    'for',
    'goto',
    'if',
    'inline',
    'register',
    'restrict',
    'return',
    'static',
    'struct',
    'switch',
    'typedef',
    'union',
    'volatile',
    'while',
  };

  static const _cppDefinition = LanguageDefinition(
    lineCommentPrefix: '//',
    blockCommentStart: '/*',
    blockCommentEnd: '*/',
    keywords: {
      ..._cKeywords,
      'catch',
      'class',
      'const_cast',
      'constexpr',
      'delete',
      'dynamic_cast',
      'explicit',
      'export',
      'friend',
      'mutable',
      'namespace',
      'new',
      'noexcept',
      'operator',
      'private',
      'protected',
      'public',
      'reinterpret_cast',
      'static_assert',
      'static_cast',
      'template',
      'this',
      'throw',
      'try',
      'typeid',
      'typename',
      'using',
      'virtual',
      'override',
      'final',
      'decltype',
      'concept',
      'requires',
      'co_await',
      'co_return',
      'co_yield',
    },
    builtinTypes: {
      'bool',
      'char',
      'wchar_t',
      'char8_t',
      'char16_t',
      'char32_t',
      'double',
      'float',
      'int',
      'long',
      'short',
      'signed',
      'unsigned',
      'void',
      'auto',
      'size_t',
      'string',
      'vector',
      'map',
      'set',
      'list',
      'deque',
      'array',
      'pair',
      'tuple',
      'shared_ptr',
      'unique_ptr',
      'weak_ptr',
      'optional',
      'variant',
      'any',
      'span',
      'string_view',
    },
    builtinConstants: {
      'true',
      'false',
      'nullptr',
      'NULL',
    },
  );

  static const _yamlDefinition = LanguageDefinition(
    hashComment: true,
    lineCommentPrefix: '#',
    keywords: {},
    builtinConstants: {
      'true',
      'false',
      'null',
      'yes',
      'no',
      'on',
      'off',
    },
  );
}
