name: dunebox_host
description: Host-side library for DuneBox (Flutter)
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dunebox_protocol:
    path: ../dunebox_protocol
  meta: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
