name: goox_terminal
description: Simple terminal wrapper for Flutter using xterm and flutter_pty.
version: 0.2.0
homepage: https://github.com/yourusername/goox_terminal

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pty: ^0.4.2
  xterm: ^4.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


