// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attach_output`, `close`, `control_byte`, `mark_activity`, `now_ms`, `refresh_exit_state`, `registry`, `resize`, `resolve_shell`, `send_signal`, `set_status`, `snapshot`, `spawn`, `to_native_size`, `validate_request`, `validate`, `wait_for_exit`, `write_bytes`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TerminalSessionRuntime`, `TerminalSignal`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Creates a new terminal session and returns its session identifier.
Future<String> createSession({required TerminalSpawnRequest request}) =>
    RustLib.instance.api.crateApiTerminalCreateSession(request: request);

/// Returns the latest snapshot for a managed terminal session.
Future<TerminalSessionSnapshot> sessionSnapshot({required String sessionId}) =>
    RustLib.instance.api.crateApiTerminalSessionSnapshot(sessionId: sessionId);

/// Lists all managed terminal sessions.
Future<List<TerminalSessionSnapshot>> listSessions() =>
    RustLib.instance.api.crateApiTerminalListSessions();

/// Attaches a listener to terminal output.
Stream<Uint8List> attachOutput({required String sessionId}) =>
    RustLib.instance.api.crateApiTerminalAttachOutput(sessionId: sessionId);

/// Writes raw bytes into the terminal input stream.
Future<int> writeInput({required String sessionId, required List<int> data}) =>
    RustLib.instance.api
        .crateApiTerminalWriteInput(sessionId: sessionId, data: data);

/// Resizes the terminal to the requested rows and columns.
Future<void> resizeSession(
        {required String sessionId, required int rows, required int cols}) =>
    RustLib.instance.api.crateApiTerminalResizeSession(
        sessionId: sessionId, rows: rows, cols: cols);

/// Sends a terminal signal to the process.
Future<void> sendSignal(
        {required String sessionId, required int signalNumber}) =>
    RustLib.instance.api.crateApiTerminalSendSignal(
        sessionId: sessionId, signalNumber: signalNumber);

/// Waits for the terminal process to exit and returns the exit code.
Future<int> waitForExit({required String sessionId}) =>
    RustLib.instance.api.crateApiTerminalWaitForExit(sessionId: sessionId);

/// Closes a managed terminal session and releases all native resources.
Future<void> closeSession({required String sessionId}) =>
    RustLib.instance.api.crateApiTerminalCloseSession(sessionId: sessionId);

class TerminalSessionSnapshot {
  final String sessionId;
  final TerminalSessionStatus status;
  final int? pid;
  final int? exitCode;
  final String shell;
  final List<String> args;
  final String? workingDirectory;
  final Map<String, String> environment;
  final int rows;
  final int cols;
  final bool attached;
  final PlatformInt64 createdAtMs;
  final PlatformInt64? startedAtMs;
  final PlatformInt64? lastActivityAtMs;

  const TerminalSessionSnapshot({
    required this.sessionId,
    required this.status,
    this.pid,
    this.exitCode,
    required this.shell,
    required this.args,
    this.workingDirectory,
    required this.environment,
    required this.rows,
    required this.cols,
    required this.attached,
    required this.createdAtMs,
    this.startedAtMs,
    this.lastActivityAtMs,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      status.hashCode ^
      pid.hashCode ^
      exitCode.hashCode ^
      shell.hashCode ^
      args.hashCode ^
      workingDirectory.hashCode ^
      environment.hashCode ^
      rows.hashCode ^
      cols.hashCode ^
      attached.hashCode ^
      createdAtMs.hashCode ^
      startedAtMs.hashCode ^
      lastActivityAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalSessionSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          status == other.status &&
          pid == other.pid &&
          exitCode == other.exitCode &&
          shell == other.shell &&
          args == other.args &&
          workingDirectory == other.workingDirectory &&
          environment == other.environment &&
          rows == other.rows &&
          cols == other.cols &&
          attached == other.attached &&
          createdAtMs == other.createdAtMs &&
          startedAtMs == other.startedAtMs &&
          lastActivityAtMs == other.lastActivityAtMs;
}

enum TerminalSessionStatus {
  starting,
  running,
  exited,
  closed,
  failed,
  ;
}

class TerminalSpawnRequest {
  final String? shell;
  final List<String> args;
  final String? workingDirectory;
  final Map<String, String> environment;
  final int rows;
  final int cols;

  const TerminalSpawnRequest({
    this.shell,
    required this.args,
    this.workingDirectory,
    required this.environment,
    required this.rows,
    required this.cols,
  });

  @override
  int get hashCode =>
      shell.hashCode ^
      args.hashCode ^
      workingDirectory.hashCode ^
      environment.hashCode ^
      rows.hashCode ^
      cols.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TerminalSpawnRequest &&
          runtimeType == other.runtimeType &&
          shell == other.shell &&
          args == other.args &&
          workingDirectory == other.workingDirectory &&
          environment == other.environment &&
          rows == other.rows &&
          cols == other.cols;
}
