// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'extensions.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'lsp.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'terminal.dart';

Future<void> seedDocument({required String text}) =>
    RustLib.instance.api.crateApiSeedDocument(text: text);

Future<BufferSnapshot> getSnapshot() =>
    RustLib.instance.api.crateApiGetSnapshot();

Future<BufferPatchBatch> applyTransaction({
  required BufferTransaction transaction,
}) => RustLib.instance.api.crateApiApplyTransaction(transaction: transaction);

Future<BufferPatchBatch> undo() => RustLib.instance.api.crateApiUndo();

Future<BufferPatchBatch> redo() => RustLib.instance.api.crateApiRedo();

Future<ViewportSnapshot> getViewport({required ViewportRequest request}) =>
    RustLib.instance.api.crateApiGetViewport(request: request);

Future<CursorPos> getCursorPosition({required BigInt charIndex}) =>
    RustLib.instance.api.crateApiGetCursorPosition(charIndex: charIndex);

Future<BufferPatchBatch> deleteLine({required BigInt charIndex}) =>
    RustLib.instance.api.crateApiDeleteLine(charIndex: charIndex);

Future<BigInt> refreshWorkspaceExtensions({required String workspaceRoot}) =>
    RustLib.instance.api.crateApiRefreshWorkspaceExtensions(
      workspaceRoot: workspaceRoot,
    );

Future<bool> activateExtensionForFile({
  required String workspaceRoot,
  required String filePath,
}) => RustLib.instance.api.crateApiActivateExtensionForFile(
  workspaceRoot: workspaceRoot,
  filePath: filePath,
);

Future<ExtensionInfo?> extensionForFile({
  required String workspaceRoot,
  required String filePath,
}) => RustLib.instance.api.crateApiExtensionForFile(
  workspaceRoot: workspaceRoot,
  filePath: filePath,
);

Future<int> erpOpenSession({
  required String workspaceRoot,
  required String filePath,
}) => RustLib.instance.api.crateApiErpOpenSession(
  workspaceRoot: workspaceRoot,
  filePath: filePath,
);

Future<int> erpGetPageCount({required int sessionId}) =>
    RustLib.instance.api.crateApiErpGetPageCount(sessionId: sessionId);

Future<String> erpRenderPageArtifact({
  required int sessionId,
  required int pageIndex,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiErpRenderPageArtifact(
  sessionId: sessionId,
  pageIndex: pageIndex,
  width: width,
  height: height,
);

Future<Uint8List> erpRenderPage({
  required int sessionId,
  required int pageIndex,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiErpRenderPage(
  sessionId: sessionId,
  pageIndex: pageIndex,
  width: width,
  height: height,
);

Future<Uint8List> erpReadArtifact({
  required int sessionId,
  required BigInt artifactId,
}) => RustLib.instance.api.crateApiErpReadArtifact(
  sessionId: sessionId,
  artifactId: artifactId,
);

Future<void> erpCloseSession({required int sessionId}) =>
    RustLib.instance.api.crateApiErpCloseSession(sessionId: sessionId);

Future<String?> erpGetMetadata({required int sessionId}) =>
    RustLib.instance.api.crateApiErpGetMetadata(sessionId: sessionId);

Future<List<String>> erpDrainEvents({required int sessionId}) =>
    RustLib.instance.api.crateApiErpDrainEvents(sessionId: sessionId);

Future<String?> validateSourceText({
  required String languageId,
  required String text,
}) => RustLib.instance.api.crateApiValidateSourceText(
  languageId: languageId,
  text: text,
);

Future<List<String>> registeredExtensionCommands() =>
    RustLib.instance.api.crateApiRegisteredExtensionCommands();

Future<bool> syncLanguageServer({
  String? workspaceRoot,
  String? filePath,
  String? languageId,
  String? lspExecutable,
  required String text,
}) => RustLib.instance.api.crateApiSyncLanguageServer(
  workspaceRoot: workspaceRoot,
  filePath: filePath,
  languageId: languageId,
  lspExecutable: lspExecutable,
  text: text,
);

Future<LanguageServerSnapshot> pollLanguageServer() =>
    RustLib.instance.api.crateApiPollLanguageServer();

Future<void> shutdownLanguageServer() =>
    RustLib.instance.api.crateApiShutdownLanguageServer();

Future<List<LanguageServerLocation>> lspFindDefinitions({
  required BigInt charIndex,
}) => RustLib.instance.api.crateApiLspFindDefinitions(charIndex: charIndex);

Future<List<LanguageServerLocation>> lspFindDeclarations({
  required BigInt charIndex,
}) => RustLib.instance.api.crateApiLspFindDeclarations(charIndex: charIndex);

Future<List<LanguageServerLocation>> lspFindImplementations({
  required BigInt charIndex,
}) => RustLib.instance.api.crateApiLspFindImplementations(charIndex: charIndex);

Future<List<LanguageServerLocation>> lspFindReferences({
  required BigInt charIndex,
}) => RustLib.instance.api.crateApiLspFindReferences(charIndex: charIndex);

Future<LanguageServerHover?> lspGetHover({required BigInt charIndex}) =>
    RustLib.instance.api.crateApiLspGetHover(charIndex: charIndex);

Future<List<LanguageServerDocumentHighlight>> lspGetDocumentHighlights({
  required BigInt charIndex,
}) =>
    RustLib.instance.api.crateApiLspGetDocumentHighlights(charIndex: charIndex);

Future<BigInt> createTerminal({
  required int rows,
  required int cols,
  String? workingDirectory,
}) => RustLib.instance.api.crateApiCreateTerminal(
  rows: rows,
  cols: cols,
  workingDirectory: workingDirectory,
);

Future<void> sendTerminalInput({
  required BigInt id,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiSendTerminalInput(id: id, bytes: bytes);

Future<TerminalScreenSnapshot> pollTerminalScreen({required BigInt id}) =>
    RustLib.instance.api.crateApiPollTerminalScreen(id: id);

Future<void> resizeTerminal({
  required BigInt id,
  required int rows,
  required int cols,
}) =>
    RustLib.instance.api.crateApiResizeTerminal(id: id, rows: rows, cols: cols);

Future<void> disposeTerminal({required BigInt id}) =>
    RustLib.instance.api.crateApiDisposeTerminal(id: id);

class CursorPos {
  final BigInt line;
  final BigInt column;

  const CursorPos({required this.line, required this.column});

  @override
  int get hashCode => line.hashCode ^ column.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CursorPos &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          column == other.column;
}
