// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            Future<void>  seedDocument({required String text }) => RustLib.instance.api.crateApiSeedDocument(text: text);

Future<BufferSnapshot>  getSnapshot() => RustLib.instance.api.crateApiGetSnapshot();

Future<BufferPatchBatch>  applyTransaction({required BufferTransaction transaction }) => RustLib.instance.api.crateApiApplyTransaction(transaction: transaction);

Future<BufferPatchBatch>  undo() => RustLib.instance.api.crateApiUndo();

Future<BufferPatchBatch>  redo() => RustLib.instance.api.crateApiRedo();

Future<ViewportSnapshot>  getViewport({required ViewportRequest request }) => RustLib.instance.api.crateApiGetViewport(request: request);

Future<CursorPos>  getCursorPosition({required BigInt charIndex }) => RustLib.instance.api.crateApiGetCursorPosition(charIndex: charIndex);

Future<BufferPatchBatch>  deleteLine({required BigInt charIndex }) => RustLib.instance.api.crateApiDeleteLine(charIndex: charIndex);

Future<BigInt>  refreshWorkspaceExtensions({required String workspaceRoot }) => RustLib.instance.api.crateApiRefreshWorkspaceExtensions(workspaceRoot: workspaceRoot);

Future<bool>  activateExtensionForFile({required String workspaceRoot , required String filePath }) => RustLib.instance.api.crateApiActivateExtensionForFile(workspaceRoot: workspaceRoot, filePath: filePath);

Future<List<String>>  registeredExtensionCommands() => RustLib.instance.api.crateApiRegisteredExtensionCommands();

            class CursorPos  {
                final BigInt line;
final BigInt column;

                const CursorPos({required this.line ,required this.column ,});

                
                

                
        @override
        int get hashCode => line.hashCode^column.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is CursorPos &&
                runtimeType == other.runtimeType
                && line == other.line&& column == other.column;
        
            }
            