// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ExtensionInfo {
  final String name;
  final String path;
  final String? entry;
  final String? webEntry;
  final List<String> filetypes;
  final String? languageId;
  final String? lspExecutable;
  final String uiMode;
  final String protocol;
  final List<String> capabilities;
  final bool rendering;

  const ExtensionInfo({
    required this.name,
    required this.path,
    this.entry,
    this.webEntry,
    required this.filetypes,
    this.languageId,
    this.lspExecutable,
    required this.uiMode,
    required this.protocol,
    required this.capabilities,
    required this.rendering,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      path.hashCode ^
      entry.hashCode ^
      webEntry.hashCode ^
      filetypes.hashCode ^
      languageId.hashCode ^
      lspExecutable.hashCode ^
      uiMode.hashCode ^
      protocol.hashCode ^
      capabilities.hashCode ^
      rendering.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtensionInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          entry == other.entry &&
          webEntry == other.webEntry &&
          filetypes == other.filetypes &&
          languageId == other.languageId &&
          lspExecutable == other.lspExecutable &&
          uiMode == other.uiMode &&
          protocol == other.protocol &&
          capabilities == other.capabilities &&
          rendering == other.rendering;
}
