// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BufferTransaction dco_decode_box_autoadd_buffer_transaction(dynamic raw);

  @protected
  ViewportRequest dco_decode_box_autoadd_viewport_request(dynamic raw);

  @protected
  BufferError dco_decode_buffer_error(dynamic raw);

  @protected
  BufferOperation dco_decode_buffer_operation(dynamic raw);

  @protected
  BufferPatchBatch dco_decode_buffer_patch_batch(dynamic raw);

  @protected
  BufferSnapshot dco_decode_buffer_snapshot(dynamic raw);

  @protected
  BufferTransaction dco_decode_buffer_transaction(dynamic raw);

  @protected
  CursorPos dco_decode_cursor_pos(dynamic raw);

  @protected
  List<BufferOperation> dco_decode_list_buffer_operation(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ViewportLine> dco_decode_list_viewport_line(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ViewportLine dco_decode_viewport_line(dynamic raw);

  @protected
  ViewportRequest dco_decode_viewport_request(dynamic raw);

  @protected
  ViewportSnapshot dco_decode_viewport_snapshot(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BufferTransaction sse_decode_box_autoadd_buffer_transaction(
    SseDeserializer deserializer,
  );

  @protected
  ViewportRequest sse_decode_box_autoadd_viewport_request(
    SseDeserializer deserializer,
  );

  @protected
  BufferError sse_decode_buffer_error(SseDeserializer deserializer);

  @protected
  BufferOperation sse_decode_buffer_operation(SseDeserializer deserializer);

  @protected
  BufferPatchBatch sse_decode_buffer_patch_batch(SseDeserializer deserializer);

  @protected
  BufferSnapshot sse_decode_buffer_snapshot(SseDeserializer deserializer);

  @protected
  BufferTransaction sse_decode_buffer_transaction(SseDeserializer deserializer);

  @protected
  CursorPos sse_decode_cursor_pos(SseDeserializer deserializer);

  @protected
  List<BufferOperation> sse_decode_list_buffer_operation(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ViewportLine> sse_decode_list_viewport_line(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ViewportLine sse_decode_viewport_line(SseDeserializer deserializer);

  @protected
  ViewportRequest sse_decode_viewport_request(SseDeserializer deserializer);

  @protected
  ViewportSnapshot sse_decode_viewport_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_buffer_transaction(
    BufferTransaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_viewport_request(
    ViewportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_buffer_error(BufferError self, SseSerializer serializer);

  @protected
  void sse_encode_buffer_operation(
    BufferOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_buffer_patch_batch(
    BufferPatchBatch self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_buffer_snapshot(
    BufferSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_buffer_transaction(
    BufferTransaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cursor_pos(CursorPos self, SseSerializer serializer);

  @protected
  void sse_encode_list_buffer_operation(
    List<BufferOperation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_viewport_line(
    List<ViewportLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_viewport_line(ViewportLine self, SseSerializer serializer);

  @protected
  void sse_encode_viewport_request(
    ViewportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_viewport_snapshot(
    ViewportSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
