// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

@freezed
sealed class BufferError with _$BufferError implements FrbException {
  const BufferError._();

  const factory BufferError.emptyTransaction() = BufferError_EmptyTransaction;
  const factory BufferError.invalidInsertPosition({
    required BigInt charIndex,
    required BigInt lenChars,
  }) = BufferError_InvalidInsertPosition;
  const factory BufferError.invalidDeleteRange({
    required BigInt start,
    required BigInt end,
    required BigInt lenChars,
  }) = BufferError_InvalidDeleteRange;
  const factory BufferError.noUndoEntry() = BufferError_NoUndoEntry;
  const factory BufferError.noRedoEntry() = BufferError_NoRedoEntry;
}

@freezed
sealed class BufferOperation with _$BufferOperation {
  const BufferOperation._();

  const factory BufferOperation.insert({
    required BigInt charIndex,
    required String text,
  }) = BufferOperation_Insert;
  const factory BufferOperation.delete({
    required BigInt start,
    required BigInt end,
  }) = BufferOperation_Delete;
}

class BufferPatchBatch {
  final BigInt revision;
  final String label;
  final List<BufferOperation> patches;

  const BufferPatchBatch({
    required this.revision,
    required this.label,
    required this.patches,
  });

  @override
  int get hashCode => revision.hashCode ^ label.hashCode ^ patches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BufferPatchBatch &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          label == other.label &&
          patches == other.patches;
}

class BufferSnapshot {
  final BigInt revision;
  final BigInt lineCount;
  final BigInt charCount;

  const BufferSnapshot({
    required this.revision,
    required this.lineCount,
    required this.charCount,
  });

  @override
  int get hashCode =>
      revision.hashCode ^ lineCount.hashCode ^ charCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BufferSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          lineCount == other.lineCount &&
          charCount == other.charCount;
}

class BufferTransaction {
  final List<BufferOperation> operations;
  final bool mergeable;
  final String label;

  const BufferTransaction({
    required this.operations,
    required this.mergeable,
    required this.label,
  });

  @override
  int get hashCode => operations.hashCode ^ mergeable.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BufferTransaction &&
          runtimeType == other.runtimeType &&
          operations == other.operations &&
          mergeable == other.mergeable &&
          label == other.label;
}

class ViewportLine {
  final BigInt lineIndex;
  final String text;

  const ViewportLine({required this.lineIndex, required this.text});

  @override
  int get hashCode => lineIndex.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportLine &&
          runtimeType == other.runtimeType &&
          lineIndex == other.lineIndex &&
          text == other.text;
}

class ViewportRequest {
  final BigInt firstLine;
  final BigInt maxLines;

  const ViewportRequest({required this.firstLine, required this.maxLines});

  @override
  int get hashCode => firstLine.hashCode ^ maxLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportRequest &&
          runtimeType == other.runtimeType &&
          firstLine == other.firstLine &&
          maxLines == other.maxLines;
}

class ViewportSnapshot {
  final BigInt revision;
  final BigInt firstVisibleLine;
  final BigInt totalLines;
  final List<ViewportLine> lines;

  const ViewportSnapshot({
    required this.revision,
    required this.firstVisibleLine,
    required this.totalLines,
    required this.lines,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      firstVisibleLine.hashCode ^
      totalLines.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportSnapshot &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          firstVisibleLine == other.firstVisibleLine &&
          totalLines == other.totalLines &&
          lines == other.lines;
}
