name: simple_editor
description: "Lightweight playground for goox editor primitives."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  goox_editor_sdk:
    path: ../../packages/goox_editor_sdk
  goox_ui_shared:
    path: ../../packages/goox_ui_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  goox_flutter_bridge:
    path: ../../platform/flutter_bridge

flutter:
  uses-material-design: true
