name: goox_editor_sdk
description: "High-level Dart API for goox editor apps."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.3
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  goox_flutter_bridge:
    path: ../../platform/flutter_bridge

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
