name: pdf_viewer_extension
description: Goox sample PDF viewer extension built with Flutter.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
