// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class DebugNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 500
    let windowHeight: Int = 300

    // MARK: - Window Title
    let windowTitle: String = "Goox"

    // MARK: - Animation control
    let withAnimation: Bool = true

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_debug.png"
    let imageWidth: Int = 200
    let imageHeight: Int = 200
}
