import 'package:goox_editor_engine/src/client/editor_core_client.dart';
import 'package:goox_editor_engine/src/exceptions/editor_core_exception.dart';
import 'package:goox_editor_engine/src/models/editor_patch.dart';
import 'package:goox_editor_engine/src/models/editor_view_state.dart';
import 'package:goox_editor_engine/src/models/language_server_hover.dart';
import 'package:goox_editor_engine/src/models/language_server_location.dart';

// TODO(integration): Replace with actual flutter_rust_bridge generated types
/// Placeholder for the Rust bridge class that will be generated by
/// flutter_rust_bridge.
///
/// This will be replaced with the actual generated bridge class once
/// flutter_rust_bridge code generation is set up.
abstract class RustBridge {
  /// Placeholder method for opening a file in the Rust backend.
  Future<Object> openFile({required String filePath});

  /// Placeholder method for applying a patch in the Rust backend.
  Future<Object> applyPatch({required Map<String, dynamic> patch});

  /// Placeholder method for getting view state from the Rust backend.
  Future<Object> getViewState({required String filePath});

  /// Placeholder method for closing a file in the Rust backend.
  Future<void> closeFile({required String filePath});

  /// Placeholder method for getting hover information from the Rust backend.
  Future<Object?> getHover({
    required String filePath,
    required Map<String, dynamic> location,
  });

  /// Placeholder method for getting diagnostics from the Rust backend.
  Future<List<Object>> getDiagnostics({required String filePath});

  /// Placeholder method for disposing the Rust backend.
  Future<void> dispose();
}

/// Implementation of [EditorCoreClient] using Rust backend via
/// flutter_rust_bridge.
///
/// This class provides concrete implementations of all editor core operations
/// by communicating with the Rust backend through FFI (Foreign Function
/// Interface). All Rust bridge calls are wrapped in try-catch blocks to
/// convert errors into [EditorCoreException] with descriptive messages.
///
/// ## Error Handling
///
/// All methods wrap flutter_rust_bridge calls in try-catch blocks and convert
/// any errors to [EditorCoreException] with:
/// - A descriptive message including operation context
/// - The original error for debugging
/// - The stack trace where the error occurred
///
/// ## Example Usage
///
/// ```dart
/// // Create a Rust bridge instance (will be generated by flutter_rust_bridge)
/// final rustBridge = createRustBridge();
///
/// // Create the client
/// final client = RustEditorCoreClient(rustBridge);
///
/// try {
///   // Open a file
///   final viewState = await client.openFile('/path/to/file.dart');
///   print('Opened: ${viewState.filePath}');
///
///   // Apply a patch
///   final patch = EditorPatch(
///     filePath: viewState.filePath,
///     startOffset: 0,
///     endOffset: 5,
///     newText: 'Hello',
///     version: viewState.version,
///   );
///   await client.applyPatch(patch);
///
///   // Close the file
///   await client.closeFile(viewState.filePath);
/// } on EditorCoreException catch (e) {
///   print('Error: ${e.message}');
/// } finally {
///   await client.dispose();
/// }
/// ```
final class RustEditorCoreClient implements EditorCoreClient {
  /// Creates a [RustEditorCoreClient] with the given Rust bridge instance.
  ///
  /// The bridge parameter should be an instance of the flutter_rust_bridge
  /// generated class that provides FFI communication with the Rust backend.
  RustEditorCoreClient(this._bridge);

  /// The flutter_rust_bridge instance used for FFI communication.
  final RustBridge _bridge;

  @override
  Future<EditorViewState> openFile(String filePath) async {
    try {
      final result = await _bridge.openFile(filePath: filePath);
      return EditorViewState.fromRust(result);
    } catch (e, stackTrace) {
      throw EditorCoreException(
        message: 'Failed to open file: $filePath',
        originalError: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<EditorViewState> applyPatch(EditorPatch patch) async {
    try {
      final rustPatch = patch.toRust();
      final result = await _bridge.applyPatch(patch: rustPatch);
      return EditorViewState.fromRust(result);
    } catch (e, stackTrace) {
      throw EditorCoreException(
        message: 'Failed to apply patch to ${patch.filePath}. '
            'Expected version: ${patch.version}',
        originalError: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<EditorViewState> getViewState(String filePath) async {
    try {
      final result = await _bridge.getViewState(filePath: filePath);
      return EditorViewState.fromRust(result);
    } catch (e, stackTrace) {
      throw EditorCoreException(
        message: 'Failed to get view state for file: $filePath',
        originalError: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<void> closeFile(String filePath) async {
    try {
      await _bridge.closeFile(filePath: filePath);
    } catch (e, stackTrace) {
      throw EditorCoreException(
        message: 'Failed to close file: $filePath',
        originalError: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<LanguageServerHover?> getHover(
    String filePath,
    LanguageServerLocation location,
  ) async {
    try {
      final rustLocation = location.toRust();
      final result = await _bridge.getHover(
        filePath: filePath,
        location: rustLocation,
      );

      // Return null if no hover information is available
      if (result == null) {
        return null;
      }

      return LanguageServerHover.fromRust(result);
    } catch (e, stackTrace) {
      throw EditorCoreException(
        message: 'Failed to get hover information for $filePath '
            'at line ${location.line}, column ${location.column}',
        originalError: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<List<dynamic>> getDiagnostics(String filePath) async {
    try {
      final result = await _bridge.getDiagnostics(filePath: filePath);
      // TODO(diagnostics): Convert to proper Diagnostic type when it's defined
      // For now, return the raw list from Rust
      return result;
    } catch (e, stackTrace) {
      throw EditorCoreException(
        message: 'Failed to get diagnostics for file: $filePath',
        originalError: e,
        stackTrace: stackTrace,
      );
    }
  }

  @override
  Future<void> dispose() async {
    try {
      await _bridge.dispose();
    } catch (e, stackTrace) {
      throw EditorCoreException(
        message: 'Failed to dispose editor core client',
        originalError: e,
        stackTrace: stackTrace,
      );
    }
  }
}
